services:
  factorio:
    build:
      context: .
      args:
        # Check buildinfo.json for supported versions and SHAs
        # https://github.com/factoriotools/factorio-docker/blob/master/buildinfo.json
        - VERSION=1.1.110
        - SHA256=485fe6db36e5decd7dd0d70e7c97e61f818100fa3e48d87884b287027c7a646a
    ports:
      - "34197:34197/udp"
      - "27015:27015/tcp"
    volumes:
      - /opt/factorio:/factorio
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - UPDATE_MODS_ON_START=true
#      - USERNAME=FactorioUsername
#      - TOKEN=FactorioToken
#      - PORT=34198
#      - PRESET=deathworld
#      - ADDR=::1
